---
- hosts: NWM-KUB01
  become: true
  tasks:
  - name: Get Certificate
    slurp:
      src: /opt/cert-store/alpx-wildcard.crt
    register: certificate
    

  - name: Get Key
    slurp:
      src: /opt/cert-store/alpx-wildcard.key
    register: key

  - name: set facts
    set_fact: 
      decoded_certificate: "{{ certificate['content'] | b64decode }}"
      decoded_key: "{{ key['content'] | b64decode }}"
    

- hosts: f5
  connection: local
  gather_facts: false
  vars:
    F5_Cert_Name: alpacx.be
    files_loc: /opt/cert-store
    provider:
     server: 172.16.200.245
     user: "root"
     password: "Nwmoes123!"
     server_port: 443
     validate_certs: "no"
  tasks:
#SSL Upload and Modification of VIP to use New Certificate
  - name: SSL cert upload
    bigip_ssl_certificate:
      provider: "{{provider}}"
      name: "{{F5_Cert_Name}}"
      content: "{{ hostvars['NWM-KUB01']['decoded_certificate'] }}"
    

  - name: SSL key upload
    bigip_ssl_key:
      provider: "{{provider}}"
      name: "{{F5_Cert_Name}}"
      state: present
      content: "{{ hostvars['NWM-KUB01']['decoded_key'] }}"

  - name: Create a client SSL profile with a cert/key/chain setting
    bigip_profile_client_ssl:
      provider: "{{provider}}"
      state: present
      name: "{{F5_Cert_Name}}"
      cert_key_chain:
       - cert: "{{F5_Cert_Name}}"
         key: "{{F5_Cert_Name}}"

 