---
- name: Cert Management on BIG-IP
  hosts: f5
  connection: local
  gather_facts: false
  vars:
    F5_VIP_Name: www.alpacx.be
    files_loc: /opt/cert-store
    provider:
     server: 172.16.200.245
#      user: admin
#      password: supersecretPW
     user: "root"
     password: "Nwmoes123!"
     server_port: 443
     validate_certs: "no"

  tasks:
  - name: Get Certificate
    slurp:
      src: /opt/cert-store/www.alpacx.be.crt
      delegate_to: NWM-KUB01.alpacx.be
    register: certificate
    

  - name: Get Key
    slurp:
      src: /opt/cert-store/www.alpacx.be.key
    register: key
    delegate_to: NWM-KUB01.alpacx.be

#SSL Upload and Modification of VIP to use New Certificate
  - name: SSL cert upload
    bigip_ssl_certificate:
      provider: "{{provider}}"
      name: "{{F5_VIP_Name}}_Cert"
      content: "{{ certificate['content'] | b64decode }}"
    

  - name: SSL key upload
    bigip_ssl_key:
      provider: "{{provider}}"
      name: "{{F5_VIP_Name}}_Key"
      state: present
      content: "{{ key['content'] | b64decode }}"

  - name: Create a client SSL profile with a cert/key/chain setting
    bigip_profile_client_ssl:
      provider: "{{provider}}"
      state: present
      name: "{{F5_VIP_Name}}_ClientSSL_profile"
      cert_key_chain:
       - cert: "{{F5_VIP_Name}}_Cert"
         key: "{{F5_VIP_Name}}_Key"
