---
- hosts: NWM-KUB01
  become: true
  tasks:
  - name: Get Certificate
    slurp:
      src: /opt/cert-store/alpx-wildcard.crt
    register: certificate

  - name: set facts
    set_fact: 
      decoded_certificate: "{{ certificate['content'] | b64decode }}"

- hosts: f5
  connection: local
  gather_facts: false
  vars:
    F5_Cert_Name: alpacx.be
    files_loc: /opt/cert-store
    provider:
     server: 172.16.200.245
     user: "root"
     password: "Nwmoes123!"
     server_port: 443
     validate_certs: "no"
  tasks:
## New SSL Instal
  - name: SSL cert upload
    bigip_ssl_certificate:
      provider: "{{provider}}"
      name: "{{F5_Cert_Name}}"
      content: "{{ hostvars['NWM-KUB01']['decoded_certificate'] }}"